apiVersion: v1
kind: Service
metadata:
  name: random-shapes-svc
  namespace: my-app-namespace
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: random-shapes
  type: NodePort
